/*
///////////////////////////////////////////////////////////////
//
// This file can be run as an SQL query to create the sample
// database for the videostore application. However, it will not
// populate the tables. In order to do that, I recommend using
// the "databaseBackup.sql" file
//
////////////////////////////////////////////////////////////////
*/



-- MySQL Script generated by MySQL Workbench
-- 04/14/16 23:50:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema videostoremodel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema videostoremodel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `videostoremodel` DEFAULT CHARACTER SET utf8 ;
USE `videostoremodel` ;

-- -----------------------------------------------------
-- Table `videostoremodel`.`customer_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videostoremodel`.`customer_table` (
  `Cust_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Last_name` VARCHAR(20) NOT NULL,
  `Middle_initial` VARCHAR(1) NULL DEFAULT NULL,
  `First_name` VARCHAR(20) NOT NULL,
  `Street_number` INT(8) NOT NULL,
  `Street_name` VARCHAR(25) NOT NULL,
  `Apt_unit` VARCHAR(10) NULL DEFAULT NULL,
  `City` VARCHAR(25) NOT NULL,
  `State` VARCHAR(2) NOT NULL,
  `Zip` INT(5) NOT NULL,
  `Email` VARCHAR(50) NULL DEFAULT NULL,
  `Member_join` VARCHAR(15) NOT NULL,
  `Member_cancel` VARCHAR(15) NULL DEFAULT NULL,
  `Phone_number` VARCHAR(10) NULL DEFAULT NULL,
  `Movies_rented` INT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`Cust_id`),
  UNIQUE INDEX `idtable1_UNIQUE` (`Cust_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videostoremodel`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videostoremodel`.`employees` (
  `User_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(20) NOT NULL,
  `Employee_last_name` VARCHAR(20) NOT NULL,
  `Employee_middle_initial` VARCHAR(1) NULL DEFAULT NULL,
  `Employee_first_name` VARCHAR(20) NOT NULL,
  `Active` ENUM('Y', 'N') NULL DEFAULT 'Y',
  `Password` VARCHAR(10) NULL DEFAULT NULL,
  `Privelage_type` ENUM('General_Manager', 'Administrator', 'Assistant_Manager', 'Clerk', 'Accountant') NOT NULL DEFAULT 'Clerk',
  UNIQUE INDEX `User_ID_UNIQUE` (`User_ID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `videostoremodel`.`video_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videostoremodel`.`video_table` (
  `Movie_id` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Amount_inventory` INT(2) UNSIGNED NOT NULL,
  `Movie_title` VARCHAR(85) NOT NULL,
  `Release_date` VARCHAR(25) NULL DEFAULT NULL,
  `Format` VARCHAR(45) NULL DEFAULT NULL,
  `Director_last_name` VARCHAR(45) NULL DEFAULT NULL,
  `Director_first_name` VARCHAR(45) NULL DEFAULT NULL,
  `Runtime(minutes)` INT(8) NULL DEFAULT NULL,
  `Category` ENUM('horror', 'comedy', 'action', 'documentary', 'drama', 'romance', 'mystery', 'western', 'musical', 'family', 'sci-fi', 'sports', 'animated', 'indie', 'foreign') NULL DEFAULT NULL,
  `Production_company` VARCHAR(50) NULL DEFAULT NULL,
  `Rating` ENUM('NR', 'G', 'PG', 'PG-13', 'R', 'NC-17', 'TV-Y', 'TV-Y7', 'TV-Y7FV', 'TV-G', 'TV-PG', 'TV-14', 'TV-MA') NULL DEFAULT NULL,
  PRIMARY KEY (`Movie_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videostoremodel`.`rental_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videostoremodel`.`rental_table` (
  `Rental_ref_num` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cust_id` INT(10) UNSIGNED NOT NULL,
  `Movie_id` INT(20) UNSIGNED NOT NULL,
  `Check_out_date` VARCHAR(15) NOT NULL,
  `Return_due_date` VARCHAR(15) NULL DEFAULT NULL,
  `Returned_date` VARCHAR(15) NULL DEFAULT NULL,
  `Rental_fee` DOUBLE(3,2) NOT NULL,
  `Per_diem_late_fee` DOUBLE(3,2) NOT NULL,
  `Last_updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Rental_ref_num`),
  UNIQUE INDEX `Rental_ref_num_UNIQUE` (`Rental_ref_num` ASC),
  INDEX `w_idx` (`Movie_id` ASC),
  INDEX `Cust_id_idx` (`Cust_id` ASC),
  CONSTRAINT `Cust_id`
    FOREIGN KEY (`Cust_id`)
    REFERENCES `videostoremodel`.`customer_table` (`Cust_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Movie_id`
    FOREIGN KEY (`Movie_id`)
    REFERENCES `videostoremodel`.`video_table` (`Movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 75
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
